// Code generated by docs/sky/gen_daytable.py; DO NOT EDIT.
// Regenerate: python docs/sky/gen_daytable.py  (needs meeus.py + PyEphem;
// never runs on CI, touches no MPQs -- Article V). Source: Meeus 1998
// (sun rise/set, moon phase), PyEphem (moonrise, lit %), and the C3
// computus/menologion (weekday, Easter offsets, feast/fast names).
// Controls passed at generation: instrument audit, reproduction (17 Jun
// sunset 19:50 LMT = signed S1 Appendix A), negative (1 Jan != slice).

package d2world

// sliceDayTable is the six-night slice (17-23 June 1462, Julian) in
// Targoviste local mean time. Minute fields are minute-of-day, [0,1440);
// MoonriseMinute is -1 when the moon does not rise before sunrise.
var sliceDayTable = []DayEntry{
	{Year: 1462, Month: 6, Day: 17, Weekday: "Thursday", Feast: "9th Thursday after Easter", FeastDetail: "Mart. Manuel, Sabel and Ismael", FastRule: "oil and wine, no fish", MoonPhase: "waning gibbous", SunriseMinute: 253, SunsetMinute: 1190, MoonriseMinute: 1410, MoonLitPercent: 69.3},
	{Year: 1462, Month: 6, Day: 18, Weekday: "Friday", Feast: "Apostles' Fast", FeastDetail: "Mart. Leontius", FastRule: "xerophagy (no oil or wine)", MoonPhase: "waning gibbous", SunriseMinute: 253, SunsetMinute: 1190, MoonriseMinute: 1431, MoonLitPercent: 60.3},
	{Year: 1462, Month: 6, Day: 19, Weekday: "Saturday", Feast: "Apostles' Fast", FeastDetail: "Apostle Jude (Thaddeus), brother of the Lord", FastRule: "fish, wine, oil", MoonPhase: "waning gibbous", SunriseMinute: 254, SunsetMinute: 1190, MoonriseMinute: 11, MoonLitPercent: 50.8},
	{Year: 1462, Month: 6, Day: 20, Weekday: "Sunday", Feast: "2nd Sunday after Pentecost", FeastDetail: "Hieromart. Methodius of Patara", FastRule: "fish, wine, oil", MoonPhase: "waning crescent", SunriseMinute: 254, SunsetMinute: 1190, MoonriseMinute: 31, MoonLitPercent: 41.3},
	{Year: 1462, Month: 6, Day: 21, Weekday: "Monday", Feast: "Apostles' Fast", FeastDetail: "Mart. Julian of Tarsus", FastRule: "xerophagy (no oil or wine)", MoonPhase: "waning crescent", SunriseMinute: 255, SunsetMinute: 1190, MoonriseMinute: 52, MoonLitPercent: 32.0},
	{Year: 1462, Month: 6, Day: 22, Weekday: "Tuesday", Feast: "Apostles' Fast", FeastDetail: "Hieromart. Eusebius of Samosata", FastRule: "oil and wine", MoonPhase: "waning crescent", SunriseMinute: 255, SunsetMinute: 1189, MoonriseMinute: 74, MoonLitPercent: 23.1},
	{Year: 1462, Month: 6, Day: 23, Weekday: "Wednesday", Feast: "Apostles' Fast", FeastDetail: "Mart. Agrippina of Rome", FastRule: "xerophagy (no oil or wine)", MoonPhase: "waning crescent", SunriseMinute: 256, SunsetMinute: 1189, MoonriseMinute: 101, MoonLitPercent: 15.2},
}
